DROP TABLE IF EXISTS School;
CREATE TABLE School(
    id INT NOT NULL AUTO_INCREMENT  COMMENT '主键ID' ,
    school_name VARCHAR(32) NOT NULL   COMMENT '门派名称' ,
    delete_flag TINYINT NOT NULL   COMMENT '是否已删除/弃用' ,
    CREATED_USER VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATED_USER VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_BY VARCHAR(32)    COMMENT '删除人' ,
    DELETE_TIME DATETIME    COMMENT '删除时间' ,
    PRIMARY KEY (id)
)  COMMENT = '门派';

DROP TABLE IF EXISTS QATemplate;
CREATE TABLE QATemplate(
    id INT NOT NULL AUTO_INCREMENT  COMMENT '主键' ,
    name VARCHAR(32) NOT NULL   COMMENT '模板名称/问题名称' ,
    school_id INT NOT NULL   COMMENT '门派ID' ,
    categroy_type INT NOT NULL   COMMENT '分类层级' ,
    father_id INT NOT NULL   COMMENT '父ID' ,
    default_flag TINYINT NOT NULL   COMMENT '是否默认模板' ,
    delete_flag TINYINT NOT NULL   COMMENT '是否已删除' ,
    CREATED_USER VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATED_USER VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_BY VARCHAR(32)    COMMENT '删除人' ,
    DELETE_TIME DATETIME    COMMENT '删除时间' ,
    PRIMARY KEY (id)
)  COMMENT = '问答模板';

